src/UnusedPlugin.php

I just remove a unused class here. Both unused packages and classes should be removed, aren't they! :smiley: 
This is an awesome package. Let me give a hand.
Thank you!

Remove unused class

---

src/Command/UnusedCommand.php

"by scanning by comparing" -> "by scanning and comparing"

Fix command description

---

src/Command/UnusedCommand.php
src/Error/Handler/ErrorHandlerInterface.php
tests/Integration/Command/UnusedCommandTest.php
tests/assets/TestProject/composer.json
tests/assets/TestProject/vendor/composer/installed.json
tests/assets/TestProject/vendor/package/unused-empty-namespace/composer.json

Improve exception handling in debug mode.
Kind of solve #27

Improve error handling

---

CONTRIBUTING.md

A clean explanation may look like pretty

Detail CONTRIBUTING

---

README.md

I imagine that I am a new one who wants to use this package and try to make the documentation nicer.
I also help to fix some typo such as "of you required composer packages".

Clean README

---

src/Loader/Factory/PackageLoaderFactory.php

Yii2 extensions use [yii2-extension](https://www.yiiframework.com/doc/guide/2.0/en/structure-extensions#package-type) package type. I added this type to the filter, so the plugin will accept these packages.
```
$ composer unused
Loading packages
----------------
6/6 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
! [NOTE] Found 1 package(s) to be checked.                                                                             
Scanning files from basedir /store/Downloads/yii-application
------------------------------------------------------------
116/116 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
Results
-------
Found 1 used, 0 unused and 5 ignored packages
Used packages
✓ yiisoft/yii2
Unused packages
Ignored packages
○ php (Unable to locate package)
○ yiisoft/yii2-bootstrap (Invalid package type)
○ …
```

Add Yii2 extension support

---

composer.json
phpstan.neon
src/Di/Exception/ServiceNotCreatedException.php
src/Di/Exception/ServiceNotFoundException.php
src/Di/FactoryInterface.php
src/Di/ServiceContainer.php
src/Loader/Factory/LoaderBuilderFactory.php
src/Loader/Factory/PackageLoaderFactory.php
src/Loader/Factory/UsageLoaderFactory.php
src/Loader/LoaderBuilder.php
src/Loader/PackageLoader.php
tests/Unit/Di/ServiceContainerTest.php

This will replace `zendframework/zend-servicemanager` with custom `psr/container-interface` implemented ServiceContainer.

Remove zendframework dependency

---

.docker/php7.1/Dockerfile
.docker/php7.2/Dockerfile
.docker/php7.3/Dockerfile
composer.json
src/Command/UnusedCommand.php
src/Loader/Factory/PackageLoaderFactory.php
src/Loader/Filter/NullPackageFilter.php
src/Loader/PackageHelper.php
src/Loader/PackageLoader.php
src/Parser/Factory/NodeVisitorFactory.php
src/Parser/Strategy/PhpExtensionStrategy.php
tests/Integration/Loader/PackageLoaderTest.php
tests/Integration/Parser/NodeVisitorTest.php
tests/Unit/Loader/Filter/NullPackageFilterTest.php
tests/Unit/Loader/PackageHelperTest.php
tests/assets/TestFiles/PhpExtensionStrategy/ClassWithCustomConstant.php
tests/assets/TestFiles/PhpExtensionStrategy/ClassWithCustomFunction.php
tests/assets/TestFiles/PhpExtensionStrategy/ClassWithCustomInterface.php
tests/assets/TestFiles/PhpExtensionStrategy/ClassWithCustomInterfaceName.php
tests/assets/TestFiles/PhpExtensionStrategy/ClassWithExtensionFunction.php
tests/assets/TestFiles/PhpExtensionStrategy/ClassWithExtensionInterface.php
tests/assets/TestFiles/PhpExtensionStrategy/ClassWithExtensionInterfaceInUse.php
tests/assets/TestFiles/PhpExtensionStrategy/ClassWithJsonConstant.php
tests/assets/TestFiles/PhpExtensionStrategy/ClassWithZendOpcache.php

** No because your 0.x branch is not up to date
This should fix #33

analyse ext packages

---

README.md

This PR fixes the image size on smaller viewports.
2. [ ] Have you lint your code locally prior to submission?

Fix size of logo for small viewports

---

README.md

Fix typo and usage example

---

CHANGELOG.md
README.md
src/Command/UnusedCommand.php
src/Loader/LoaderInterface.php
src/Loader/PackageLoader.php
src/Loader/PrograssBarTrait.php
src/Loader/UsageLoader.php

Add no-progress option

---

.gitattributes

Add docker on export-ignore

---

CHANGELOG.md
composer.json
src/Command/UnusedCommand.php
src/UnusedPlugin.php

Add composer ^2.0 support.
Solve #76

Add support for composer ^2.0

---

CHANGELOG.md
src/Parser/PHP/Strategy/ExtendsParseStrategy.php
src/Parser/PHP/Strategy/ImplementsParseStrategy.php
tests/Integration/Parser/PHP/NodeVisitorTest.php
tests/assets/TestFiles/ClassExtendsFQN.php
tests/assets/TestFiles/ClassImplements.php

Fix packages marked unused using FQN

---

composer.json
src/Command/UnusedCommand.php
src/Dependency/DependencyInterface.php
src/Dependency/InvalidDependency.php
src/Dependency/RequiredDependency.php
tests/Unit/Dependency/RequiredDependencyTest.php

Add check for cross requirements

---

composer.json
src/Command/UnusedCommand.php
src/Dependency/DependencyInterface.php
src/Dependency/InvalidDependency.php
src/Dependency/RequiredDependency.php
tests/Unit/Dependency/RequiredDependencyTest.php

Add check for cross suggestion

---

composer.json

Allow psr/log v2 and v3

---

CONTRIBUTING.md

while installing the project I noticed that the up command was missing in CONTRIBUTING.md

added missing up command

---

composer.json

2. [ ] Have you lint your code locally prior to submission?

Allow support for psr/container ^2.0

---

src/Filter/FilterCollection.php

Exlude composer-unused-plugin from being reported as unused

---

.github/workflows/validate-code.yml
CHANGELOG.md
composer.json
phpunit.bootstrap.php
src/Composer/Link.php
src/Composer/LocalRepository.php
src/Composer/Package.php
src/Composer/PackageFactory.php
src/Console/Command/UnusedCommand.php
src/Dependency/RequiredDependency.php
src/OutputFormatter/DefaultFormatter.php
src/OutputFormatter/FormatterFactory.php
src/OutputFormatter/GithubFormatter.php
src/OutputFormatter/OutputFormatterInterface.php
tests/Unit/Composer/PackageFactoryTest.php
tests/Unit/Dependency/RequiredDependencyTest.php

Add --output-format

---

CHANGELOG.md
README.md
box.json
composer-unused.php
composer.json
src/Command/CollectConsumedSymbolsCommand.php
src/Command/Handler/CollectConsumedSymbolsCommandHandler.php
src/Command/Handler/CollectRequiredDependenciesCommandHandler.php
src/Command/LoadRequiredDependenciesCommand.php
src/Configuration/Configuration.php
src/Configuration/FilterInterface.php
src/Configuration/NamedFilter.php
src/Configuration/PatternFilter.php
src/Console/Command/UnusedCommand.php
src/Dependency/DependencyCollection.php
src/Filter/FilterCollection.php
src/Filter/NamedFilter.php
src/Filter/PatternFilter.php
src/Symbol/ConsumedSymbolLoaderBuilder.php
src/Symbol/ProvidedSymbolLoaderBuilder.php
tests/Integration/UnusedCommandTest.php
tests/Unit/Filter/NamedFilterTest.php
tests/Unit/Filter/PatternFilterTest.php
tests/assets/TestProjects/DependencyWithAdditionalFile/composer-unused.php
tests/assets/TestProjects/DependencyWithAdditionalFile/composer.json
tests/assets/TestProjects/DependencyWithAdditionalFile/src/TestClass.php
tests/assets/TestProjects/DependencyWithAdditionalFile/vendor/composer/installed.json
tests/assets/TestProjects/DependencyWithAdditionalFile/vendor/test/file-dependency/composer.json
tests/assets/TestProjects/DependencyWithAdditionalFile/vendor/test/file-dependency/src/file.php

Add dedicated configuration

---

scoper.inc.php

Expose ComposerUnused\Configuration to be able to access configuration classes

---

.github/workflows/validate-code.yml
composer.json
config/polyfill_symfony_di.php
config/services.php

This should fix #358
[EDIT] It also adds a `--prefer-lowest` job in CI that made the problem appear.

Fix Symfony 4 support

---

composer-unused.php

Add missing use statement

---

composer.json
src/Console/Command/UnusedCommand.php
src/OutputFormatter/FormatterFactory.php
src/OutputFormatter/JsonFormatter.php
tests/Unit/OutputFormatter/FormatterFactoryTest.php
tests/Unit/OutputFormatter/JsonFormatter/Fixture/expected_unused_packages.json
tests/Unit/OutputFormatter/JsonFormatter/JsonFormatterTest.php

Follow up to https://github.com/composer-unused/composer-unused/pull/280#issuecomment-1265958116
So other tools can pick up the result easily and parse it to standardized json :+1:

Add JsonFormatter with test

---

.docker/php8.2/Dockerfile
.github/workflows/validate-code.yml
docker-compose.yml

While all tests run successfully there might be problems not covered. Also some dependencies of this package are not yet ready/confirmed for PHP 8.2 (installing with `composer i --ignore-platform-reqs`). Nonetheless this should make the switch easier when PHP 8.2 gets a final release.

[WIP] Prepare php 8.2 support

---

README.md

2. [ ] Have you lint your code locally prior to submission?

fixes pattern in README

---

.github/workflows/validate-code.yml
Makefile
composer.json
phpstan.neon
src/Composer/InstalledVersions.php
tests/Unit/Composer/PackageFactoryTest.php
tests/Unit/OutputFormatter/JsonFormatter/JsonFormatterTest.php

chore: bump phpstan to v1

---

src/Command/CollectConsumedSymbolsCommand.php
src/Command/Handler/CollectConsumedSymbolsCommandHandler.php
src/Console/Command/UnusedCommand.php
src/Symbol/ConsumedSymbolLoaderBuilder.php
tests/Integration/UnusedCommandTest.php
tests/assets/TestProjects/IgnoreExcludedDir/composer.json
tests/assets/TestProjects/IgnoreExcludedDir/src/Excluded/TestClass.php
tests/assets/TestProjects/IgnoreExcludedDir/vendor/composer/installed.php
tests/assets/TestProjects/IgnoreExcludedDir/vendor/test/file-dependency/composer.json
tests/assets/TestProjects/IgnoreExcludedDir/vendor/test/file-dependency/src/DependencyClass.php

Resolves https://github.com/composer-unused/composer-unused/issues/418

fix: reimplement excludeDir

---

src/Console/Command/UnusedCommand.php

Use correct version in CLI

---

composer.json
composer.lock
tests/Integration/UnusedCommandTest.php
tests/assets/TestProjects/MissingPSR4Directory/composer.json
tests/assets/TestProjects/MissingPSR4Directory/vendor/composer/installed.php

Avoid exception on missing directory

---

src/OutputFormatter/GithubFormatter.php
tests/Unit/OutputFormatter/GithubFormatter/Fixture/expected_unused_packages.txt
tests/Unit/OutputFormatter/GithubFormatter/GithubFormatterTest.php

Avoid github pr info on ignored packages

---

composer.json
composer.lock
src/Symbol/ConsumedSymbolLoaderBuilder.php
src/Symbol/ProvidedSymbolLoaderBuilder.php

Follow-up to composer-unused/symbol-parser#92.

Pass NameResolver to SymbolNameParser

---

src/Console/Command/DebugConsumedSymbolsCommand.php
src/Console/Command/DebugProvidedSymbolsCommand.php

Add composer-json option to debug commands to allow usage from outside root project.

Add composer-json option to debug

---

src/Command/Handler/CollectConsumedSymbolsCommandHandler.php

Fix #462
The filtering of root namespaces causes an issue
that on any given "rootPackage" with the same NamespacePrefix as any subpackage the consumed symbols for that subpackage are removed.
E.g:
root -> "Main\\":"src/"
package -> "Main\\Package\\":"src/"
The package will be marked as unused which should not

Remove root namespace filter to avoid subpackage filtering

---

composer.json
composer.lock
src/Composer/Config.php
src/Composer/InstalledVersions.php
src/Composer/InvalidPackage.php
src/Composer/LocalRepository.php
src/Composer/LocalRepositoryFactory.php
src/Composer/Package.php
src/Composer/PackageFactory.php
src/Console/Command/UnusedCommand.php
src/Dependency/DependencyInterface.php
src/Dependency/RequiredDependency.php
src/OutputFormatter/DefaultFormatter.php
tests/Stubs/TestDependency.php
tests/Unit/Dependency/RequiredDependencyTest.php

Add hyperlink to default formatter

---

composer.json
composer.lock
tests/Integration/UnusedCommandTest.php

Add polyfill for extension ds

---

.github/dependabot.yaml

This should now disable updates outside development and also ignore major updates correctly
2. [ ] Have you lint your code locally prior to submission?

Fix dependabot configuration issues

---

.github/workflows/release-phar.yml
.github/workflows/validate-phar.yml
.gitignore
bin/composer-unused
box.json

Add ability to automatically determine version

---

src/Composer/PackageFactory.php
tests/Unit/Composer/PackageFactoryTest.php

Issue_559: strip slashes

---

composer.json
composer.lock

chore(deps): require composer-unused/symbol-parser v0.2.2

---

src/Command/Handler/CollectRequiredDependenciesCommandHandler.php
src/Console/Progress/DefaultProgressBarDecorator.php
src/Console/Progress/ProgressBarInterface.php

Related to my comment https://github.com/composer-unused/composer-unused/issues/610#issuecomment-1986802316

Display package processing on right side of progress bar (in verbose mode)

---

.docker/php8.1/Dockerfile
.docker/php8.2/Dockerfile
.docker/php8.3/Dockerfile
.docker/php8.4/Dockerfile
.github/workflows/validate-code.yml
tests/Integration/UnusedCommandTest.php
tests/assets/TestProjects/ExtHttpRequirement/composer.json
tests/assets/TestProjects/ExtHttpRequirement/src/TestClass.php
tests/assets/TestProjects/ExtHttpRequirement/vendor/composer/installed.php
tests/assets/TestProjects/ExtZipRequirement/composer.json
tests/assets/TestProjects/ExtZipRequirement/src/TestClass.php
tests/assets/TestProjects/ExtZipRequirement/vendor/composer/installed.php

fix: Add tests to cover extensions marked unused

---

composer.json
composer.lock
tests/Integration/UnusedCommandTest.php
tests/assets/TestProjects/ExtMemcachedRequirement/composer.json
tests/assets/TestProjects/ExtMemcachedRequirement/src/TestClass.php
tests/assets/TestProjects/ExtMemcachedRequirement/vendor/composer/installed.php

fix: Resolve issue with memcached marked unused

---

.actrc
.claude/settings.local.json
.github/workflows/release-phar.yml
.github/workflows/validate-phar.yml
.gitignore
act-usage.md
composer.lock
vendor-bin/box/composer.lock

Also install act to local run/debug github actions

chore: Use 8.1 for build and phar validation
