tests/Unit/Subject/PackageSubjectTest.php

'ForpackageAutoload' is invalid camel-case.
By the way, do you think "checkWhetherPackageProvidesNamespace' is more clearly?

Fix test method camel case

---

src/Command/UnusedCommand.php

The autoload section contains both directories and files depends on each type below:
- psr-0 (folder based)
- psr-4 (folder based)
- classmap (folders and files)
- files (files only)
See https://github.com/icanhazstring/composer-unused/pull/6 for more details!
`loadUsages` method contains 2 steps:
1. Looking for all directories and files of autoload composer section.
2. Getting usage packages:
1. If both autoload directories and files are empty, raise an error 'Could not load paths from root package to scan.'
2. Otherwise, return the listing of usage packages.
Therefore, I suggest using the new meaningful variables `$paths`, `$autoloadDirs` and `$autoloadFiles` for readable reason.

Use meaningful variables

---

README.md
src/Command/UnusedCommand.php

Fixed a typo in the command output.

Fix typo (usued => used)

---

composer.json

Add "scripts-descriptions" that gives the other developers clearly explanation of current defined scripts.
"scripts-descriptions" is also used to list scripts to the console.
```bash
$ composer run-script --list
scripts:
analyse   Use "phpstan" to the analyse static code. See phpstan.neon  
check     Check the coding covention and run the tests                
cs-check  Use "phpcs" to check the coding convention. See phpcs.xml   
cs-fix    Use "phpcbf" to fix the coding convention. See phpcs.xml    
test      Use "phpunit" to run the tests. See phpunit.xml
```

Update composer.json file

---

src/Command/UnusedCommand.php

The plugin will now always return an exit code > 0 if there are unused packages.
However, this will **NOT** change the behavior with real errors like:
- No found packages
Also we introduce a new cli argument `--ignore-exit-code`
If this is set, we ignore the unused packages and always return a clean `0` exit code.
Resolves #30

Feature: Change exitcode if unused packages are found

---

src/Command/UnusedCommand.php

Currently exitcode `1` is returned when packages are skipped. This should be the case when packages are actually unused.

fix(UnusedCommand): fail on unused packages

---

src/Loader/Factory/PackageLoaderFactory.php

* [y] Does your PR have the correct target branch? (0.x for bugfix/feature of current release)
* [y] Have you followed the guidelines in our [Contributing document](../CONTRIBUTING.md)?
* [y] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/icanhazstring/composer-unused/pulls) for the same update/change?
1. [y] Does your submission pass tests?
2. [y] Have you lint your code locally prior to submission?
* [y ] Have you added an explanation of what your changes do and why you'd like us to include them?
TYPO3 Extensions have type "typo3-cms-extension" which currently will not be evaluated with the `composer unused`. This PR adds "typo3-cms-extension" to allowed composer types, so that they get included in the scanning.
* [n] Have you written new tests for …

[FEATURE] Adds typo3-cms-extension to allowed composer package types

---

README.md
src/Command/UnusedCommand.php

This will fix short options usage on excluding dirs or packages.
The previous implementation used a two character options which doesn't work
sind the `d` after the `-x` will be interpreted as the value for `-x`.

Fix short options usage

---

.docker/php7.3/Dockerfile
.gitattributes
.gitignore
CHANGELOG.md
README.md
bin/composer-unused
box.json
composer.json
scoper.inc.php
src/UnusedPlugin.php

This relates to #61 and #62 
The following changes should be made:

[WIP] Feature: PHAR Build

---

.github/workflows/validate-code.yml
.github/workflows/validate-phar.yml
CHANGELOG.md
composer.json
src/Command/UnusedCommand.php

This should solve #82 as it was missing the `composer/composer` requirement.
Also added another workflow to verify that the build `.phar` file is working properly.

Fix missing Composer\Console\Application

---

src/Log/DebugLogger.php

Running the 0.7.2 with -vvv fails:
```
Uncaught TypeError: Argument 1 passed to Icanhazstring\Composer\Unused\Log\DebugLogger::buildRecord() must be of the type int, string given, called in vendor/icanhazstring/composer-unused/src/Log/DebugLogger.php on line 33 and defined in vendor/icanhazstring/composer-unused/src/Log/DebugLogger.php:44
Stack trace:
#0 vendor/icanhazstring/composer-unused/src/Log/DebugLogger.php(33): Icanhazstring\Composer\Unused\Log\DebugLogger->buildRecord('info', 'version', Array)
#1 phar:///usr/local/bin/composer/vendor/psr/log/Psr/Log/LoggerTrait.php(114): Icanhazstring\Composer\Unused\Log\DebugLogger->log('info', 'version', Array)
#2 vendor/icanhazstring/composer-unused/src/Command/UnusedCommand.php(274): …
```

Make log level less strictly expected from psr log

---

CHANGELOG.md
src/Parser/PHP/Factory/NodeVisitorFactory.php
src/Parser/PHP/Strategy/InstanceofStrategy.php
tests/Integration/Parser/PHP/NodeVisitorTest.php
tests/assets/TestFiles/Instanceof.php

@OskarStark and I ran into an issue in a project that requires `psr/http-message`, and where we use
```php
use Psr/Http;
if ($response instanceof Http\Message\ResponseInterface) {
}
```
However, running
```
$ composer-unused
```
results in `psr/http-message` not being used, so I figured I take a look.
Does that make sense?

Enhancement: Implement InstanceofStrategy

---

composer.json

https://github.com/advisories/GHSA-frqg-7g38-6gcf

Raise min composer version to 2.1.9 in order to prevent CVE-2021-41116

---

.docker/php8.0/Dockerfile
.docker/php8.1/Dockerfile
.github/workflows/validate-code.yml
composer.json
docker-compose.yml

Add php8.1 build

---

Makefile
src/Console/Command/UnusedCommand.php
src/Dependency/DependencyInterface.php
src/Dependency/InvalidDependency.php
src/Dependency/RequiredDependency.php
tests/Integration/UnusedCommandTest.php
tests/Unit/Dependency/RequiredDependencyTest.php

Solve #219: Add required-by output after scan

---

composer.json
src/Console/Command/UnusedCommand.php
src/Dependency/DependencyInterface.php
src/Dependency/InvalidDependency.php
src/Dependency/RequiredDependency.php

Resolve #218: Add `suggested-by` flag for console output

---

Makefile
phpstan.neon
src/Symbol/ConsumedSymbolLoaderBuilder.php
tests/Integration/UnusedCommandTest.php
tests/assets/TestProjects/FileDependencyFunctionWithGuard/composer.json
tests/assets/TestProjects/FileDependencyFunctionWithGuard/src/TestClass.php
tests/assets/TestProjects/FileDependencyFunctionWithGuard/vendor/composer/installed.json
tests/assets/TestProjects/FileDependencyFunctionWithGuard/vendor/test/file-dependency/composer.json
tests/assets/TestProjects/FileDependencyFunctionWithGuard/vendor/test/file-dependency/src/file.php

This should solve #242 using defined global function names with a guard condition.

Check for function invocation parsing

---

tests/Integration/UnusedCommandTest.php
tests/assets/TestProjects/ArrayNamespace/composer.json
tests/assets/TestProjects/ArrayNamespace/src/TestClass.php

This PR will allow multiple paths to be specified per namespace.
The first commit replicates the issue I encountered and reported in https://github.com/composer-unused/composer-unused/issues/293
Note: I just realised the root of this particular issue is outside the package. I'll try to resolve it in the `composer-unused/symbol-parser` package in the next days.
Signed-off-by: Agustin Gomes <me@agustingomes.com>

Allow list of paths for a single namespace specification

---

src/PackageResolver.php

We need to avoid strpos to allow packages containing `php` in their package name at the beginning to be found and parsed correctly
Resolve #316 #317

Avoid strpos comparison for php package

---

src/Composer/Package.php
src/Dependency/RequiredDependency.php
tests/Unit/Dependency/RequiredDependencyTest.php

Related to: https://github.com/composer-unused/composer-unused/issues/321
Hello!
My first PR here. 
Small improvement for the execution time. When checking one of the project I've made [profile ](https://blackfire.io/profiles/ffd6dc8a-9aa3-42bb-bdc9-308f947ef930/graph) - execution took 5 min 14s. It looks like iterating over the required packages is really slow - but it could be easily updated - we can improve internal logic of `Package` class to store it under associative array that reduces complexity for access time. Where is a result of this PoC - [profile](https://blackfire.io/profiles/ffd6dc8a-9aa3-42bb-bdc9-308f947ef930/graph) - execution time reduced to  3mins 49s. 
As a next step I would propose to add `public function requires(string $name): bool` method to `PackageInterface` - …

Make Required Dependencies faster

---

src/Console/Command/UnusedCommand.php

Related to: https://github.com/composer-unused/composer-unused/issues/321
After previous PR I was trying to understanding what is happening inside the loops that is causing many calls to checking relations between packages. It looks like for each file we were trying to find packages that are suggested or required by others. 
As the loop is independent on the main loop over files we can run it once before iterating over files - with the same results. 
[Baseline: 4 min 56 s ](https://blackfire.io/profiles/75280e88-ef4d-4c85-843a-52e777f15a83/graph)
[After changes: 1 min 06 s ](https://blackfire.io/profiles/00203bfc-3327-4882-a4c1-687193061a77/graph?settings%5Bdimension%5D=wt&settings%5Bdisplay%5D=landscape&settings%5BtabPane%5D=nodes&selected=&callname=main()&constraintDoc=)
[Comparison: - …

Split independent loops during looking for used packages

---

composer-unused.php
src/Filter/PatternFilter.php
tests/Unit/Filter/PatternFilterTest.php

Hey,
I noticed a small bug.
The PatternFilter does not keep the used state when a following dependency does not match.
So the filter is listed as zombie and the script ends with the error code 1.
And another little thing I noticed and I don't know if it was intentional, but the example pattern in composer-unused.php doesn't cover all Symfony components.
Greetings.

Keep the PatternFilter in used state

---

src/Console/Command/UnusedCommand.php
tests/Integration/UnusedCommandTest.php
tests/assets/TestProjects/DependencyWithAdditionalFileWithComposerUnusedInEtc/composer.json
tests/assets/TestProjects/DependencyWithAdditionalFileWithComposerUnusedInEtc/etc/composer-unused.php
tests/assets/TestProjects/DependencyWithAdditionalFileWithComposerUnusedInEtc/src/TestClass.php
tests/assets/TestProjects/DependencyWithAdditionalFileWithComposerUnusedInEtc/vendor/composer/installed.php
tests/assets/TestProjects/DependencyWithAdditionalFileWithComposerUnusedInEtc/vendor/test/file-dependency/composer.json
tests/assets/TestProjects/DependencyWithAdditionalFileWithComposerUnusedInEtc/vendor/test/file-dependency/src/file.php

The configuration option is there but never wired up to be used
Refs: https://github.com/WyriHaximus/php-test-utilities/pull/603
1. [X] Does your submission pass tests?
2. [X] Have you lint your code locally prior to submission?

Wire up custom configuration file location support

---

src/Filter/FilterCollection.php

Fixes: https://github.com/composer-unused/composer-unused/issues/381

Mark new "composer" platform requirement as globally excluded. (Fixes: #381)

---

config/services.php

For PHP version 8.1.3 the `PHP_VERSION_ID` is `80103`.
This fixes the issue reported in https://github.com/composer-unused/composer-unused/issues/326.

Lexer version detector patch

---

src/Console/Command/UnusedCommand.php
tests/Integration/UnusedCommandTest.php

override exit code with "0" if option `--ignore-exit-code` is used

---

tests/Integration/UnusedCommandTest.php
tests/assets/TestProjects/DependencyWithReadonlyClass/composer.json
tests/assets/TestProjects/DependencyWithReadonlyClass/src/TestClass.php
tests/assets/TestProjects/DependencyWithReadonlyClass/vendor/composer/installed.php
tests/assets/TestProjects/DependencyWithReadonlyClass/vendor/test/file-dependency/composer.json
tests/assets/TestProjects/DependencyWithReadonlyClass/vendor/test/file-dependency/src/DependencyClass.php

This PR adds a testcase for a readonly dependency as suggested in issue #369.

Add testcase for readonly class (#369)

---

src/Command/Handler/CollectConsumedSymbolsCommandHandler.php
src/Console/Command/UnusedCommand.php
tests/Integration/UnusedCommandTest.php
tests/assets/TestProjects/EmptyPSR4Namespace/composer.json
tests/assets/TestProjects/EmptyPSR4Namespace/src/TestClass.php
tests/assets/TestProjects/EmptyPSR4Namespace/vendor/composer/installed.php
tests/assets/TestProjects/EmptyPSR4Namespace/vendor/test/file-dependency/composer.json
tests/assets/TestProjects/EmptyPSR4Namespace/vendor/test/file-dependency/src/file.php

Fix #342 - Empty PSR4 namespace

---

composer.json

This tells composer to install composer-unused to require-dev when running composer require without --dev https://github.com/composer/composer/pull/10960

Add "static analysis" tag

---

.github/ISSUE_TEMPLATE/bug-report.md
bin/composer-unused
config/services.php
src/Command/Handler/CollectRequiredDependenciesCommandHandler.php
src/Configuration/ConfigurationProvider.php
src/Console/Command/DebugConsumedSymbolsCommand.php
src/Console/Command/DebugProvidedSymbolsCommand.php
src/Console/Command/UnusedCommand.php

This will add some debug commands to composer-unused.
This should help get more information to debug false-positives.
Should help analyze problems e.g. #462 (#461)

Add debug commands to see consumed and defined symbols

---

.docker/php8.2/Dockerfile
.github/workflows/validate-code.yml

I saw that the Dockerfile for 8.2 was using the RC image. I changed that up. 
And if I edit the GitHub action file correctly, it should now be required to pass. I haven't done much with GitHub action, so let me know if something is wrong.

Use stable 8.2 docker image

---

src/Console/Command/UnusedCommand.php
src/OutputFormatter/FormatterFactory.php
src/OutputFormatter/GitlabFormatter.php
tests/Unit/OutputFormatter/FormatterFactoryTest.php
tests/Unit/OutputFormatter/GilabFormatter/Fixture/expected_unused_packages.txt
tests/Unit/OutputFormatter/GilabFormatter/GitlabFormatterTest.php

Hi,
This PR adds a Gitlab output formatter to this project. This can be used with the code quality checks inside a Gitlab Ci envirement.
If you have feedback, I would be happy to hear them!

feat: add gitlab output formatter

---

composer.json
composer.lock
src/Configuration/AdditionalFilesAlreadySetException.php
src/Configuration/Configuration.php
tests/Unit/Configuration/ConfigurationTest.php

This will raise an exception when Configuration::setAdditionalFileFor is called multiple times. This should give the user a hint on how to add multiple files.
Resolve #513 

Improve user experience when adding additional files

---

src/Console/Command/DebugProvidedSymbolsCommand.php

While `debug:consumed-symbols` command results are sorted in ascending order with PHP [sort](https://www.php.net/manual/en/function.sort) function and default SORT_REGULAR option.
`debug:provided-symbols` command did not have the same behavior.
This PR apply the same behavior on both commands.

Sort results of `debug:provided-symbols` command

---

composer.json
composer.lock
config/services.php
phpstan-baseline.neon
phpstan.neon
src/Symbol/ConsumedSymbolLoaderBuilder.php
src/Symbol/ProvidedSymbolLoaderBuilder.php

Make the Core code of this package compatible with [PHP-Parser](https://github.com/nikic/PHP-Parser) v5 and ready for a new version of `composer-unused/symbol-parser` [also compatible v5](https://github.com/composer-unused/symbol-parser/pull/133)

Add support to PHP-Parser v5

---

src/Console/Command/UnusedCommand.php
src/OutputFormatter/CompactFormatter.php
src/OutputFormatter/FormatterFactory.php
tests/Unit/OutputFormatter/CompactFormatter/CompactFormatterTest.php

Add a compact formatter, that only prints single lines with errors

Add a compact formatter

---

CLAUDE.md
README.md
bin/composer-unused
composer-unused.php
composer.json
composer.lock

- Integrates `composer/xdebug-handler` to automatically disable XDebug when composer-unused runs
- Prevents segmentation faults that occur with XDebug 3.4.3 and certain method chaining syntax patterns
- Provides transparent performance improvement for all users with XDebug installed
- Allows users to override with `COMPOSER_UNUSED_ALLOW_XDEBUG=1` environment variable when debugging is needed
- Added `composer/xdebug-handler` dependency
- Integrated XDebug handler in main entry point (`bin/composer-unused`)
- Updated documentation (README.md and CLAUDE.md) with XDebug handling information
- Added conventional commit standards to CLAUDE.md
- ✅ Coding standards check passes
- ✅ PHPStan analysis passes
- ✅ No breaking changes to existing functionality
Fixes #688
This solution follows the …

fix: automatically disable XDebug to prevent segmentation faults
